# This is a basic workflow to help you get started with Actions

name: CI/CD practice
run-name: ${{ github.actor }} is testing out GitHub Actions

env:
  GITHUB_ACTIONS: "running"

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "github-task-job"
  github-task-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "Workflow run status ${{ env.GITHUB_ACTIONS }}"
      - run: echo "Name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
      - run: echo "The job was triggered by a ${{ github.event_name }} event"
